# Generated by Django 5.1.6 on 2025-02-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_game_alter_myuser_options_gamestats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
