# Generated by Django 5.1.6 on 2025-03-03 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_gamestats_options_alter_myuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Player Goal',
                'verbose_name_plural': 'Player Goals',
            },
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='goals',
        ),
        migrations.AddField(
            model_name='gamestats',
            name='numeric_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='player_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.playergoal'),
        ),
        migrations.CreateModel(
            name='RankSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_numeric', models.BooleanField(default=False)),
                ('max_numeric_value', models.IntegerField(blank=True, null=True)),
                ('increment', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_systems', to='base.game')),
            ],
            options={
                'verbose_name': 'Rank System',
                'verbose_name_plural': 'Rank Systems',
                'unique_together': {('game', 'name')},
            },
        ),
        migrations.AddField(
            model_name='gamestats',
            name='rank_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_stats', to='base.ranksystem'),
        ),
        migrations.CreateModel(
            name='RankTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('rank_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='base.ranksystem')),
            ],
            options={
                'ordering': ['rank_system', 'order'],
                'unique_together': {('rank_system', 'order')},
            },
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ranktier'),
        ),
    ]
