# Generated by Django 5.1.6 on 2025-03-03 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_playergoal_remove_gamestats_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranktier',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload rank icon (JPEG, PNG, or GIF)', null=True, upload_to='rank_icons/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload game logo (JPEG, PNG, or GIF)', null=True, upload_to='game_logos/'),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='hours_played',
            field=models.IntegerField(default=0, help_text='Total hours played in this game', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='numeric_rank',
            field=models.IntegerField(blank=True, help_text='Points for numeric ranking systems (e.g., CS2 Premier points)', null=True),
        ),
        migrations.AlterField(
            model_name='playergoal',
            name='description',
            field=models.TextField(help_text='Detailed description of what this player goal means'),
        ),
        migrations.AlterField(
            model_name='playergoal',
            name='name',
            field=models.CharField(help_text="Name of the player goal (e.g., 'Competitive', 'Casual')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ranksystem',
            name='increment',
            field=models.IntegerField(blank=True, help_text='Step size for numeric ranks (e.g., 1000 for CS2 Premier)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ranksystem',
            name='is_numeric',
            field=models.BooleanField(default=False, help_text='Check if this is a points-based system (like CS2 Premier)'),
        ),
        migrations.AlterField(
            model_name='ranksystem',
            name='max_numeric_value',
            field=models.IntegerField(blank=True, help_text='Maximum value for numeric ranks', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ranktier',
            name='order',
            field=models.IntegerField(help_text='Position in the ranking system (1 being lowest)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
