# Generated by Django 5.1.6 on 2025-03-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_ranktier_icon_alter_game_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='timezone_offset',
            field=models.IntegerField(default=0, help_text='Timezone offset in hours from UTC'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='active_hours',
            field=models.JSONField(blank=True, default=list, help_text="Array of active hours in 24-hour format (e.g., ['00:00', '01:00'])"),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='language_preference',
            field=models.JSONField(blank=True, default=list, help_text='Array of preferred languages'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='platforms',
            field=models.JSONField(blank=True, default=list, help_text='Array of gaming platforms'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='social_links',
            field=models.JSONField(blank=True, default=list, help_text='Array of social media links'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='timezone',
            field=models.CharField(blank=True, help_text="User's timezone (e.g., 'UTC', 'America/New_York')", max_length=50, null=True),
        ),
    ]
