# Generated by Django 5.1.6 on 2025-03-04 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_myuser_timezone_offset_alter_myuser_active_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestats',
            name='numeric_rank',
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='rank_system',
        ),
        migrations.CreateModel(
            name='GameRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_rank', models.IntegerField(blank=True, help_text='Points for numeric ranking systems (e.g., CS2 Premier points)', null=True)),
                ('game_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='base.gamestats')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ranktier')),
                ('rank_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_rankings', to='base.ranksystem')),
            ],
            options={
                'verbose_name': 'Game Ranking',
                'verbose_name_plural': 'Game Rankings',
                'unique_together': {('game_stats', 'rank_system')},
            },
        ),
    ]
