# Generated by Django 5.1.6 on 2025-03-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_message_is_delivered_messagereaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageReaction',
        ),
    ]
