# Generated by Django 5.1.6 on 2025-04-03 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_delete_messagereaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Коментар', 'verbose_name_plural': 'Коментари'},
        ),
        migrations.AlterModelOptions(
            name='gameranking',
            options={'verbose_name': 'Ранг на играч', 'verbose_name_plural': 'Рангове на играчи'},
        ),
        migrations.AlterModelOptions(
            name='gamestats',
            options={'verbose_name': 'Статистика за игра', 'verbose_name_plural': 'Статистики за игри'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Харесване', 'verbose_name_plural': 'Харесвания'},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Потребител', 'verbose_name_plural': 'Потребители'},
        ),
        migrations.AlterModelOptions(
            name='playergoal',
            options={'verbose_name': 'Цел на играч', 'verbose_name_plural': 'Цели на играчи'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterModelOptions(
            name='ranksystem',
            options={'verbose_name': 'Ранг система', 'verbose_name_plural': 'Ранг системи'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_edited',
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, help_text='Качи лого на играта (JPEG, PNG, или GIF)', null=True, upload_to='game_logos/'),
        ),
        migrations.AlterField(
            model_name='gameranking',
            name='numeric_rank',
            field=models.IntegerField(blank=True, help_text='Точки за числови ранкинг системи (напр. CS2 Premier точки)', null=True),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='hours_played',
            field=models.IntegerField(default=0, help_text='Общо изиграни часове в тази игра', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='active_hours',
            field=models.JSONField(blank=True, default=list, help_text="Масив от активни часове в 24-часов формат (напр. ['00:00', '01:00'])"),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='language_preference',
            field=models.JSONField(blank=True, default=list, help_text='Масив от предпочитани езици'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='platforms',
            field=models.JSONField(blank=True, default=list, help_text='Масив от геймърски платформи'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='social_links',
            field=models.JSONField(blank=True, default=list, help_text='Масив от връзки към социални мрежи'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='timezone',
            field=models.CharField(blank=True, help_text="Часова зона на потребителя (напр. 'UTC', 'Europe/Sofia')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='timezone_offset',
            field=models.IntegerField(default=0, help_text='Отместване в часове от UTC'),
        ),
        migrations.AlterField(
            model_name='playergoal',
            name='description',
            field=models.TextField(help_text='Подробно описание на това какво означава тази цел'),
        ),
        migrations.AlterField(
            model_name='playergoal',
            name='name',
            field=models.CharField(help_text="Име на целта на играча (напр. 'Състезателно', 'Забавление')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ranksystem',
            name='increment',
            field=models.IntegerField(blank=True, help_text='Стъпка за числови рангове (напр. 1000 за CS2 Premier)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ranksystem',
            name='is_numeric',
            field=models.BooleanField(default=False, help_text='Отбележи, ако това е точкова система (като CS2 Premier)'),
        ),
        migrations.AlterField(
            model_name='ranksystem',
            name='max_numeric_value',
            field=models.IntegerField(blank=True, help_text='Максимална стойност за числови рангове', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ranktier',
            name='icon',
            field=models.ImageField(blank=True, help_text='Качи икона на ранга (JPEG, PNG, или GIF)', null=True, upload_to='rank_icons/'),
        ),
        migrations.AlterField(
            model_name='ranktier',
            name='order',
            field=models.IntegerField(help_text='Позиция в ранкинг системата (1 е най-ниската)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
